---
title: 'Reproducible Research: Peer Assessment 2'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

The following package is used for this analysis:

```{r, warning=FALSE, message=FALSE}
library(ggplot2)
library(sqldf)
library(grid)
library(gridExtra)
```

## Loading and preprocessing the data

In order to load the data from "activity.csv", read.csv will is used:

```{r cache = TRUE}
data <- read.csv(bzfile("repdata-data-StormData.csv.bz2"))
```

FATALITIES AND INJURIES:

```{r cache = TRUE}
# Fatalities
ct_fat <- sqldf("select UPPER(EVTYPE) EVTYPE, SUM(FATALITIES) count from data 
                where FATALITIES>0 group by UPPER(EVTYPE) 
                order by 2 desc")

ct_fat[grepl("AVAL",ct_fat$EVTYPE),1]<- "AVALANCHE"
ct_fat[grepl("HEAT",ct_fat$EVTYPE),1]<-"HEAT/EXCESSIVE HEAT"
ct_fat[grep("TORNADO",ct_fat$EVTYPE),1] <- "TORNADO"
ct_fat[grepl("TSTM|THUNDERST",ct_fat$EVTYPE),1] <- "THUNDERSTORM WIND"
ct_fat[grepl("FLOOD",ct_fat$EVTYPE),1] <- "FLOOD"
ct_fat[grepl("LIGHTNING",ct_fat$EVTYPE),1]<-"LIGHTNING"
ct_fat[grepl("RIP",ct_fat$EVTYPE),1]<-"RIP CURRENT"
ct_fat[grepl("HIGH WIND",ct_fat$EVTYPE),1]<-"HIGH WIND" 
ct_fat[grepl("WINTER STORM",ct_fat$EVTYPE),1]<-"WINTER STORM" 
ct_fat[grepl("EXTREME COLD",ct_fat$EVTYPE),1] <-"EXTREME COLD"

FATALITIES <- sqldf("select UPPER(EVTYPE) EVENT_TYPE, sum(count) FATALITIES from ct_fat
                    group by UPPER(EVTYPE) 
                    order by 2 desc")
TOP10_FATALITIES <- head(FATALITIES,10)

# Injuries
ct_inj <- sqldf("select UPPER(EVTYPE) EVTYPE, SUM(INJURIES) count from data
                where INJURIES>0 group by UPPER(EVTYPE) 
                order by 2 desc")

ct_inj[grepl("AVAL",ct_inj$EVTYPE),1]<- "AVALANCHE"
ct_inj[grepl("HEAT",ct_inj$EVTYPE),1]<-"HEAT/EXCESSIVE HEAT"
ct_inj[grep("TORNADO",ct_inj$EVTYPE),1] <- "TORNADO"
ct_inj[grepl("TSTM|THUNDERST",ct_inj$EVTYPE),1] <- "THUNDERSTORM WIND"
ct_inj[grepl("FLOOD",ct_inj$EVTYPE),1] <- "FLOOD"
ct_inj[grepl("LIGHTNING",ct_inj$EVTYPE),1]<-"LIGHTNING"
ct_inj[grepl("RIP",ct_inj$EVTYPE),1]<-"RIP CURRENT"
ct_inj[grepl("HIGH WIND",ct_inj$EVTYPE),1]<-"HIGH WIND" 
ct_inj[grepl("WINTER STORM",ct_inj$EVTYPE),1]<-"WINTER STORM" 
ct_inj[grepl("EXTREME COLD",ct_inj$EVTYPE),1] <-"EXTREME COLD"

INJURIES <- sqldf("select UPPER(EVTYPE) EVENT_TYPE, sum(count) INJURIES from ct_inj 
                  group by UPPER(EVTYPE) order by 2 desc")
TOP10_INJURIES <- head(INJURIES,10)

# Property Damage

DMG_PROP <- sqldf("select UPPER(EVTYPE) EVTYPE, PROPDMG, UPPER(PROPDMGEXP) PROPDMGEXP from data where PROPDMG > 0")
#unique(DMG_PROP$PROPDMGEXP)
DMG_PROP$PROPDMGEXP <- as.character(DMG_PROP$PROPDMGEXP)
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "H"] <- 100
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "K"] <- 1000
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "M"] <- 1000000
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "B"] <- 1000000000
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "7"] <- 1e+07
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "6"] <- 1e+06
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "5"] <- 1e+05
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "4"] <- 1e+04
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "3"] <- 1e+03
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "2"] <- 1e+02
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "0"] <- 1
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "-"] <- 0
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == ""] <- 0
DMG_PROP$PROPDMGEXP[DMG_PROP$PROPDMGEXP == "+"] <- 0
DMG_PROP$PROPDMGEXP <- as.numeric(DMG_PROP$PROPDMGEXP)
DMG_PROP$PROPDMGVAL <- DMG_PROP$PROPDMG*DMG_PROP$PROPDMGEXP

DMG_PROP[grepl("AVAL",DMG_PROP$EVTYPE),1]<- "AVALANCHE"
DMG_PROP[grepl("HEAT",DMG_PROP$EVTYPE),1]<-"HEAT/EXCESSIVE HEAT"
DMG_PROP[grep("TORNADO",DMG_PROP$EVTYPE),1] <- "TORNADO"
DMG_PROP[grepl("TSTM|THUNDERST",DMG_PROP$EVTYPE),1] <- "THUNDERSTORM WIND"
DMG_PROP[grepl("FLOOD",DMG_PROP$EVTYPE),1] <- "FLOOD"
DMG_PROP[grepl("LIGHTNING",DMG_PROP$EVTYPE),1]<-"LIGHTNING"
DMG_PROP[grepl("RIP",DMG_PROP$EVTYPE),1]<-"RIP CURRENT"
DMG_PROP[grepl("HIGH WIND",DMG_PROP$EVTYPE),1]<-"HIGH WIND" 
DMG_PROP[grepl("WINTER STORM",DMG_PROP$EVTYPE),1]<-"WINTER STORM" 
DMG_PROP[grepl("EXTREME COLD",DMG_PROP$EVTYPE),1] <-"EXTREME COLD"
DMG_PROP[grepl("WILD",DMG_PROP$EVTYPE),1] <-"WILDFIRE"
DMG_PROP[grepl("STRONG",DMG_PROP$EVTYPE),1] <-"STRONG WIND"


PROPVAL <- sqldf("select UPPER(EVTYPE) EVENT_TYPE, sum(PROPDMGVAL) TOTAL from DMG_PROP group by UPPER(EVTYPE) order by 2 desc")
TOP10_PROPVAL <- head(PROPVAL,10)

# Crops Damage

DMG_CROP <- sqldf("select UPPER(EVTYPE) EVTYPE, CROPDMG, UPPER(CROPDMGEXP) CROPDMGEXP from data where CROPDMG > 0")
#unique(DMG_CROP$CROPDMGEXP)
DMG_CROP$CROPDMGEXP <- as.character(DMG_CROP$CROPDMGEXP)
DMG_CROP$CROPDMGEXP[DMG_CROP$CROPDMGEXP == "K"] <- 1000
DMG_CROP$CROPDMGEXP[DMG_CROP$CROPDMGEXP == "M"] <- 1000000
DMG_CROP$CROPDMGEXP[DMG_CROP$CROPDMGEXP == "B"] <- 1000000000
DMG_CROP$CROPDMGEXP[DMG_CROP$CROPDMGEXP == "0"] <- 1
DMG_CROP$CROPDMGEXP[DMG_CROP$CROPDMGEXP == ""] <- 0
DMG_CROP$CROPDMGEXP <- as.numeric(DMG_CROP$CROPDMGEXP)
DMG_CROP$CROPDMGVAL <- DMG_CROP$CROPDMG*DMG_CROP$CROPDMGEXP


DMG_CROP[grepl("AVAL",DMG_CROP$EVTYPE),1]<- "AVALANCHE"
DMG_CROP[grepl("HEAT",DMG_CROP$EVTYPE),1]<-"HEAT/EXCESSIVE HEAT"
DMG_CROP[grep("TORNADO",DMG_CROP$EVTYPE),1] <- "TORNADO"
DMG_CROP[grepl("TSTM|THUNDERST",DMG_CROP$EVTYPE),1] <- "THUNDERSTORM WIND"
DMG_CROP[grepl("FLOOD",DMG_CROP$EVTYPE),1] <- "FLOOD"
DMG_CROP[grepl("LIGHTNING",DMG_CROP$EVTYPE),1]<-"LIGHTNING"
DMG_CROP[grepl("RIP",DMG_CROP$EVTYPE),1]<-"RIP CURRENT"
DMG_CROP[grepl("HIGH WIND",DMG_CROP$EVTYPE),1]<-"HIGH WIND" 
DMG_CROP[grepl("WINTER STORM",DMG_CROP$EVTYPE),1]<-"WINTER STORM" 
DMG_CROP[grepl("EXTREME COLD",DMG_CROP$EVTYPE),1] <-"EXTREME COLD"
DMG_CROP[grepl("WILD",DMG_CROP$EVTYPE),1] <-"WILDFIRE"
DMG_CROP[grepl("STRONG",DMG_CROP$EVTYPE),1] <-"STRONG WIND"

CROPVAL <- sqldf("select UPPER(EVTYPE) EVENT_TYPE, sum(CROPDMGVAL) TOTAL from DMG_CROP group by UPPER(EVTYPE) order by 2 desc")
TOP10_CROPVAL <- head(CROPVAL,10)

```


Plots 1:

```{r cache = TRUE}
p1 <- ggplot(data=TOP10_FATALITIES, aes(x=reorder(EVENT_TYPE,FATALITIES), y=FATALITIES, fill=FATALITIES)) +
        geom_bar(stat="identity") + coord_flip() + xlab("") + 
        ylab("Total Fatalities") + 
        theme(legend.position="none")
p2 <- ggplot(data=TOP10_INJURIES, aes(x=reorder(EVENT_TYPE,INJURIES), y=INJURIES, fill=INJURIES)) +
        geom_bar(stat="identity") + coord_flip() + xlab("") + 
        ylab("Total Injuries") +
        theme(legend.position="none")

grid.arrange(p1,p2, main = "Total Fatalities and Total Injuries by Event Type")
```

Plots 2

```{r cache = TRUE}
p3 <- ggplot(data=TOP10_PROPVAL, aes(x=reorder(EVENT_TYPE,TOTAL), y=TOTAL/1e+09, fill=TOTAL)) +
        geom_bar(stat="identity") + coord_flip() + xlab("") + 
        ylab("Total Property Damage (in Billion USD)") + 
        theme(legend.position="none")
p4 <- ggplot(data=TOP10_CROPVAL, aes(x=reorder(EVENT_TYPE,TOTAL), y=TOTAL/1e+09, fill=TOTAL)) +
        geom_bar(stat="identity") + coord_flip() + xlab("") + 
        ylab("Total Crops Damage (in Billion USD)") + 
        theme(legend.position="none")

grid.arrange(p3,p4, main = "Total Property Damage and Total Crops Damage by Event Type")
```



The End
